
	      /* This file is automatically generated */
	      package it.unisa.ofvd.utils;
	          
	      public class VersionBuild {
	        static final public String buildnum = "75";
	        static final public String builddate = "20-07-2021 20:43:36";  
	      }
	      